---
os: linux
dist: bionic
language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - "sudo apt-get --yes install linux-headers-$(uname -r) dkms virtualbox"
install:
  - pip install --requirement requirements.txt
  - wget https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
  - sudo dpkg --install ./vagrant_2.2.6_x86_64.deb
  - sudo apt-get --fix-broken install
before_script:
  - cd ../
  - mv ansible-role-iptables iptables
  - cd iptables
script:
  - python -m unittest discover --verbose
  - molecule test --all
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
