---
driver:
  name: docker
platforms:
  - name: instance
    image: ${TEST_IMAGE}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    keep_volumes: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        iptables_rules_ipv4: iptables.ipv4.rules
