---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: gateway
    box: debian/stretch64
    interfaces:
      - network_name: private_network
        auto_config: no
        virtualbox__intnet: test-role-iptables-inside
      - network_name: private_network
        auto_config: no
        virtualbox__intnet: test-role-iptables-dmz
      - network_name: private_network
        auto_config: no
        virtualbox__intnet: test-role-iptables-outside
  - name: inside-host
    box: debian/stretch64
    interfaces:
      - network_name: private_network
        auto_config: no
        virtualbox__intnet: test-role-iptables-inside
  - name: dmz-host
    box: debian/stretch64
    interfaces:
      - network_name: private_network
        auto_config: no
        virtualbox__intnet: test-role-iptables-dmz
  - name: outside-host
    box: debian/stretch64
    interfaces:
      - network_name: private_network
        auto_config: no
        virtualbox__intnet: test-role-iptables-outside
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: ansible-lint
