---
driver:
  name: docker
platforms:
  - name: instance
    image: ${TEST_IMAGE}
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    keep_volumes: false
