---
name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: release to Ansible Galaxy
    runs-on: ubuntu-20.04
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.3.0

      - name: set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: install requirements
        run: python -m pip install --requirement=requirements.ansible.txt

      - name: import role to Ansible Galaxy
        run: ansible-galaxy role import --api-key=${GALAXY_API_KEY} $(echo ${GITHUB_REPOSITORY} | cut -d/ -f1) $(echo ${GITHUB_REPOSITORY} | cut -d/ -f2)
        env:
          GALAXY_API_KEY: ${{ secrets.galaxy_api_key }}
