---
name: test
on:
  push:
    branches:
      - "**"
jobs:
  molecule:
    name: run Molecule tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - "geerlingguy/docker-debian11-ansible:latest"
          - "geerlingguy/docker-ubuntu2204-ansible:latest"
        scenario:
          - default
          - custom_rules
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.3.0

      - name: set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: requirements*.txt

      - name: install requirements
        run: python -m pip install --requirement=requirements.txt

      - name: run Molecule tests
        run: molecule test --scenario-name=${TEST_SCENARIO}
        env:
          TEST_IMAGE: ${{ matrix.image }}
          TEST_SCENARIO: ${{ matrix.scenario }}
